### ISSUE TITLE
Benchmark comparison with P2300 sender/receiver?

### ISSUE THREAD

**Issue by npuichigo** [buildingcpp/system#2]

**Comment by buildingcpp** [comment]
Is there an implementation that you have in mind to benchmark?

**Comment by npuichigo** [comment]
https://github.com/NVIDIA/stdexec

**Comment by mipac** [comment]
very interesting comparison

**Comment by buildingcpp** [comment]
Honestly, I will have to think about this one for a while.  I've taken a look at the repo for about an hour or so and I'm not sure that this would be an apples to apples comparison.  I'm not entirely sure that I could strip away enough of this repo to create a meaningful comparison without doing a disservice to what this library is trying to achieve.  

I'll follow up more when I get a chance to consider and express this more.

**Comment by buildingcpp** [comment]
work contracts has been moved to its own repository.  I will follow up on this there once I've presented WC at CppCon 24 and have time to document the results.
